$(function(){if(navigator.appVersion.match(/MSIE [0-9]+/))$('body').append($('<div id="ieTipsBox"><a href="/caution/upbrowser?referrer='+window.location.href+'"><span>Browser access below IE11 may cause problems such as view confusion and security. It is recommended that you upgrade your browser. </span><i>Read More</i></a></div>'))});
 $(function(){var tem47_banner_swiper=new Swiper('.tem47-banner .tem47_banner_62d7c7b54dbd80 .tem47-banner-con',{autoplay:6000,speed:1000,loop:!0,autoplayDisableOnInteraction:!1,pagination:'.tem47-banner .tem47_banner_62d7c7b54dbd80 .swiper-pagination',paginationClickable:!0,onInit:function(swiper){$(".tem47-banner .tem47_banner_62d7c7b54dbd80 .progress_bar").addClass("active")},onSlideChangeEnd:function(swiper){$(".tem47-banner .tem47_banner_62d7c7b54dbd80 .progress_bar").addClass("active")},onSlideChangeStart:function(swiper){$(".tem47-banner .tem47_banner_62d7c7b54dbd80 .progress_bar").removeClass("active")}});if($('.tem47_banner_62d7c7b54dbd80 input[module-setting="visible"]').val()=="show"){$(".tem47_banner_62d7c7b54dbd80 .text .btn").show();$(".tem47_banner_62d7c7b54dbd80 .cursor").hide()}else{$(".tem47_banner_62d7c7b54dbd80 .text .btn").hide();$(".tem47_banner_62d7c7b54dbd80 .cursor").show()}});
 $(function(){$('#i_62d7c7b566bf321 .swiper').html('<div class="swiper-container"><span class="close_"><i class="icon-clear"></i></span><div class="swiper-wrapper"></div></div>');$('#i_62d7c7b566bf321 .scrollBox li').each(function(){$(this).find('.icon-crop_free').data('index',$(this).index());if($(this).find('img').attr('src')){$('#i_62d7c7b566bf321 .swiper-wrapper').append('<div class="swiper-slide close_"><img lazy-src="'+$(this).find('img').attr('src')+'"></div>')}
if($(this).find('img').attr('lazy-src')){$('#i_62d7c7b566bf321 .swiper-wrapper').append('<div class="swiper-slide close_"><img lazy-src="'+$(this).find('img').attr('lazy-src')+'"></div>')}});var backgroundColor=$('#i_62d7c7b566bf321 .box').css('background-color'),fontColor=$('#i_62d7c7b566bf321 .box').css('color');$('#i_62d7c7b566bf321 .icons span').css({'color':backgroundColor,'border-color':fontColor});$('#i_62d7c7b566bf321 .swiper span.close_').css('color',backgroundColor);var mySwiper=new Swiper('#i_62d7c7b566bf321 .swiper-container',{preventLinksPropagation:!0});var scroll=new scrollBox('#i_62d7c7b566bf321 .scrollBox',{column:!1,column_lg:parseFloat($('#i_62d7c7b566bf321 [module-setting="column-lg"]').val()),column_md:parseFloat($('#i_62d7c7b566bf321 [module-setting="column-md"]').val()),column_sm:parseFloat($('#i_62d7c7b566bf321 [module-setting="column-sm"]').val()),column_xs:parseFloat($('#i_62d7c7b566bf321 [module-setting="column-xs"]').val()),speed:parseFloat($('#i_62d7c7b566bf321 [module-setting=speed]').val())});$('#i_62d7c7b566bf321 .close_').on('click',function(){$('#i_62d7c7b566bf321 .swiper-container').removeClass('show')});$('#i_62d7c7b566bf321 .icon-crop_free').on('click',function(){$('#i_62d7c7b566bf321 .swiper-container').addClass('show');mySwiper.slideTo($(this).data('index'),1000,!1)})});
 $(function(){var $wrap=$('.tem09-certified .tem09-certified_62d7c7b5686d222 .r_box .r_img .img_con .img .img_bg');var val=Math.tan(Math.PI/4);$wrap.each(function(i,elem){var obj2=$(this).find('span');moveDir($(this),obj2)});function moveDir(obj,obj2){if($(window).width()<990){return}
obj.hover(function(ev){initXY(ev);obj.flag=getDir();initDir(obj,obj2);obj2.stop().animate({left:0,top:0},200);img_text(obj)},function(ev){initXY(ev);obj.flag=getDir();outMove(obj2,obj)});function initXY(ev){obj.x=ev.pageX-obj.offset().left-obj.outerWidth()/2;obj.y=ev.pageY-obj.offset().top-obj.outerHeight()/2;obj.tan=-obj.y/obj.x;if(obj.x==0){obj.x=1}}
function getDir(){if((obj.tan<val&&obj.tan>-val)&&obj.x>0){return 1}else if((obj.tan>val||obj.tan<-val)&&obj.y<0){return 2}else if((obj.tan>-val&&obj.tan<val)&&obj.x<0){return 3}else{return 4}}
function initDir(obj,obj2){switch(obj.flag){case 1:obj2.css({left:obj.outerWidth(),top:0});break;case 2:obj2.css({left:0,top:-(obj.outerHeight())});break;case 3:obj2.css({left:-(obj.outerWidth()),top:0});break
default:obj2.css({left:0,top:obj.outerHeight()});break}}
function outMove(obj,obj1){switch(obj1.flag){case 1:obj.stop().animate({left:obj1.outerWidth(),top:0},200);break;case 2:obj.stop().animate({left:0,top:-(obj1.outerHeight())},200);break;case 3:obj.stop().animate({left:-(obj1.outerWidth()),top:0},200);break;default:obj.stop().animate({left:0,top:obj1.outerHeight()},200);break}}}
function img_text(obj){var img=obj.parent().find("img")[0],l_img=obj.parents(".tem09-certified").find(".l_img .img img")[0],l_title=obj.parents(".tem09-certified").find(".l_img .title");l_img.src=$(img).attr('lazy-src')||img.src;l_title.text(img.alt)}
var tem09_certified=new Swiper('.tem09-certified_62d7c7b5686d222 .center_img',{lazyLoading:!0,speed:500,loop:!0,nextButton:'.tem09-certified_62d7c7b5686d222 .img_right',prevButton:'.tem09-certified_62d7c7b5686d222 .img_left',lazyLoading:!0});$(".tem09-certified .tem09-certified_62d7c7b5686d222 .r_box .r_img .img_con ul li").click(function(){$(this).parents(".tem09-certified").find(".center_img").addClass("active");tem09_certified.slideTo($(this).index()+1,0,!1)});$(".tem09-certified .tem09-certified_62d7c7b5686d222 .center_img .searchbox").click(function(){$(this).parent().removeClass("active")});img_text($wrap.eq(0))});
 $(function(){new formIframe('62d7c7b56d3c727')});
 $(document).ready(function(){$("#inquire_form").bootstrapValidator({feedbackIcons:{valid:'icon-checkmark',invalid:'icon-cancel3',validating:'icon-refresh'},fields:{contents:{validators:{notEmpty:{message:"Do not allow empty"}}},email:{validators:{notEmpty:{message:"Do not allow empty"},emailAddress:{message:"Please enter a valid e-mail format"}}},yzm:{validators:{notEmpty:{message:"Do not allow empty"}}}}})});
 function downloadApp(){$('#download-app img').each(function(){$(this).attr('src',$(this).data('src'))})}
var userAgent=window.navigator.userAgent;if(userAgent.toLowerCase().match(/MicroMessenger/i)=='micromessenger'){$(".app-wechat").show()}else if(userAgent.indexOf("Safari")>-1&&userAgent.indexOf("iPhone")>-1){$(".app-safari").show()}else{if($(".app-android").length){$(".app-android").show()}else{$("[data-content='create-app']").hide()}};
 var mqChatFanyi=["Do not allow empty","Please enter a valid e-mail format","Name","Phone","E-mail","Content","Chat Online","verification code is incorrect","E-mail address does not exist","The sending failed, This may be a malformed format of the mailbox, Please check the following contents.","Quantity"];
 $(function(){var $class=$('.mobile_bottom');if($class.find('.icon-uniE633').parent().attr('href')=='tel:')$class.find('.icon-uniE633').parents('li').addClass('hide');if($class.find('.icon-uniE621').parent().attr('href')=='sms:')$class.find('.icon-uniE621').parents('li').addClass('hide');if($class.find('.icon-uniE63A').parent().attr('href')=='mailto:')$class.find('.icon-uniE63A').parents('li').addClass('hide');$('.mobile-bottom ul li').click(function(){$(this).find('span, i').addClass('font-color').parent('a').parent('li').siblings().find('span, i').removeClass('font-color')});$('#mobile_bottom_iquire').click(function(){if($('body').hasClass('cms_product')){if($('#cms_comment').length)$('html,body').animate({scrollTop:$('#cms_comment').offset().top-80},800);else if($('#inquire_form').length)$('html,body').animate({scrollTop:$('#inquire_form').offset().top-80},800)}else $(this).attr('href','/inquire/cart')});var _share=$('.tem01-beshare.addClass').parent('[widget-style="wrap"]');var _time=500;var timer1=null;var timer2=null;if(!_share.length||_share.hasClass('hidden')||!_share.find('li').length){$class.find('.icon-share').parents('li').addClass('hidden')};$('#mobile_bottom_share').on('click',function(){var _item=_share.find('.tem01-beshare.addClass');_item.toggleClass('on');if(_item.hasClass('on')){clearTimeout(timer2);_item.css('display','block');timer1=setTimeout(function(){_item.addClass('startAnimation')},10)}else{clearTimeout(timer1);_item.removeClass('startAnimation');timer2=setTimeout(function(){_item.css('display','none')},_time)}})});var navactive=function(activeobj){if(!$('body').hasClass('designer-body')){$('[prodetails-con]').hide();$('[prodetails-con='+activeobj+']').show()}}